"""Migración inicial

Revision ID: 1b656e643be7
Revises: 
Create Date: 2026-08-04 11:54:47.486751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '1b656e643be7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.drop_index(op.f('IX_Asistencia_Fecha'), table_name='Asistencia')
    op.create_index(op.f('ix_Asistencia_ID_Asistencia'), 'Asistencia', ['ID_Asistencia'], unique=False)
    op.drop_index(op.f('IX_Bitacora_Fecha'), table_name='Bitacora')
    op.create_index(op.f('ix_Bitacora_ID_Bitacora'), 'Bitacora', ['ID_Bitacora'], unique=False)
    op.create_index(op.f('ix_Contratos_ID_Contrato'), 'Contratos', ['ID_Contrato'], unique=False)
    op.create_index(op.f('ix_Departamentos_ID_Departamento'), 'Departamentos', ['ID_Departamento'], unique=False)
    op.alter_column('Empleados', 'Entra_ID',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('IX_Empleados_Depto'), table_name='Empleados')
    op.create_index(op.f('ix_Empleados_ID_Empleado'), 'Empleados', ['ID_Empleado'], unique=False)
    op.create_index(op.f('ix_Permisos_ID_Permiso'), 'Permisos', ['ID_Permiso'], unique=False)
    op.drop_index(op.f('IX_Planilla_Periodo'), table_name='Planilla')
    op.create_index(op.f('ix_Planilla_ID_Planilla'), 'Planilla', ['ID_Planilla'], unique=False)
    op.create_index(op.f('ix_Planilla_Deducciones_ID_Planilla_Deduccion'), 'Planilla_Deducciones', ['ID_Planilla_Deduccion'], unique=False)
    op.create_index(op.f('ix_Roles_ID_Rol'), 'Roles', ['ID_Rol'], unique=False)
    op.create_index(op.f('ix_TiposDeduccion_ID_TipoDeduccion'), 'TiposDeduccion', ['ID_TipoDeduccion'], unique=False)
    op.create_index(op.f('ix_Ubicaciones_ID_Ubicacion'), 'Ubicaciones', ['ID_Ubicacion'], unique=False)
    op.create_index(op.f('ix_Vacaciones_ID_Vacacion'), 'Vacaciones', ['ID_Vacacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Vacaciones_ID_Vacacion'), table_name='Vacaciones')
    op.drop_index(op.f('ix_Ubicaciones_ID_Ubicacion'), table_name='Ubicaciones')
    op.drop_index(op.f('ix_TiposDeduccion_ID_TipoDeduccion'), table_name='TiposDeduccion')
    op.drop_index(op.f('ix_Roles_ID_Rol'), table_name='Roles')
    op.drop_index(op.f('ix_Planilla_Deducciones_ID_Planilla_Deduccion'), table_name='Planilla_Deducciones')
    op.drop_index(op.f('ix_Planilla_ID_Planilla'), table_name='Planilla')
    op.create_index(op.f('IX_Planilla_Periodo'), 'Planilla', ['Anio', 'Mes'], unique=False)
    op.drop_index(op.f('ix_Permisos_ID_Permiso'), table_name='Permisos')
    op.drop_index(op.f('ix_Empleados_ID_Empleado'), table_name='Empleados')
    op.create_index(op.f('IX_Empleados_Depto'), 'Empleados', ['ID_Departamento'], unique=False)
    op.alter_column('Empleados', 'Entra_ID',
               existing_type=sa.String(),
               type_=mssql.UNIQUEIDENTIFIER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_Departamentos_ID_Departamento'), table_name='Departamentos')
    op.drop_index(op.f('ix_Contratos_ID_Contrato'), table_name='Contratos')
    op.drop_index(op.f('ix_Bitacora_ID_Bitacora'), table_name='Bitacora')
    op.create_index(op.f('IX_Bitacora_Fecha'), 'Bitacora', ['Fecha'], unique=False)
    op.drop_index(op.f('ix_Asistencia_ID_Asistencia'), table_name='Asistencia')
    op.create_index(op.f('IX_Asistencia_Fecha'), 'Asistencia', ['Fecha'], unique=False)
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B610ED87610'))
    )
    # ### end Alembic commands ###
